### ISSUE TITLE
Akismet: AssertionError on comment_date type

### ISSUE THREAD

**Issue by jclgoodwin** [mixkorshun/django-antispam#5]
python-akismet expects comment_date to be `datetime`, not a timestamp:

https://github.com/Nekmo/python-akismet/blob/322cf3e9a9a1986434a20e01cabb6767e91a226b/akismet/__init__.py#L49

django-antispam provides a timestamp:

https://github.com/mixkorshun/django-antispam/blob/3b193a8360ff8171f0c6d7cc1891fab0b69d0e0a/antispam/akismet/entities.py#L155

So I get an `AssertionError` when calling `akismet.check`

**Comment by mixkorshun** [comment]
Looks correct. Thanks for your contribution.
